package domain

import (
	"time"
)

// AgentType defines the specialized operational focus of an autonomous agent.
type AgentType string

const (
	TypeKnowledge    AgentType = "KNOWLEDGE_AGENT"
	TypeResearch     AgentType = "RESEARCH_AGENT"
	TypeOrganization AgentType = "ORGANIZATION_AGENT"
	TypeDocument     AgentType = "DOCUMENT_AGENT"
	TypeFinancial    AgentType = "FINANCIAL_AGENT"
	TypeTravel       AgentType = "TRAVEL_AGENT"
	TypeLearning     AgentType = "LEARNING_AGENT"
	TypeCompliance   AgentType = "COMPLIANCE_AGENT"
)

// ExecutionMode defines how the agent executes its plans.
type ExecutionMode string

const (
	ModeManualApproval ExecutionMode = "MANUAL_APPROVAL"
	ModeAutomatic      ExecutionMode = "AUTOMATIC"
	ModeScheduled      ExecutionMode = "SCHEDULED"
	ModeEventDriven    ExecutionMode = "EVENT_DRIVEN"
	ModeGoalDriven     ExecutionMode = "GOAL_DRIVEN"
)

// AgentStatus represents the state of an agent.
type AgentStatus string

const (
	StatusAgentActive  AgentStatus = "ACTIVE"
	StatusAgentPaused  AgentStatus = "PAUSED"
	StatusAgentWorking AgentStatus = "WORKING"
	StatusAgentIdle    AgentStatus = "IDLE"
	StatusAgentError   AgentStatus = "ERROR"
)

// TaskStatus represents the lifecycle state of a plan task.
type TaskStatus string

const (
	TaskPending          TaskStatus = "PENDING"
	TaskAwaitingApproval TaskStatus = "AWAITING_APPROVAL"
	TaskApproved         TaskStatus = "APPROVED"
	TaskRejected         TaskStatus = "REJECTED"
	TaskRunning          TaskStatus = "RUNNING"
	TaskCompleted        TaskStatus = "COMPLETED"
	TaskFailed           TaskStatus = "FAILED"
)

// Agent represents an autonomous collaborator.
type Agent struct {
	ID            string        `json:"id"`
	UserID        string        `json:"user_id"`
	Name          string        `json:"name"`
	Type          AgentType     `json:"type"`
	Description   string        `json:"description"`
	Status        AgentStatus   `json:"status"`
	ExecutionMode ExecutionMode `json:"execution_mode"`
	Permissions   []string      `json:"permissions"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

// AgentGoal represents a persistent goal configured by the user.
type AgentGoal struct {
	ID          string    `json:"id"`
	AgentID     string    `json:"agent_id"`
	UserID      string    `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Schedule    string    `json:"schedule"` // e.g. "0 2 * * *" or "CONTINUOUS"
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// AgentPlan represents a multi-step execution plan generated by the planning engine.
type AgentPlan struct {
	ID             string      `json:"id"`
	GoalID         string      `json:"goal_id"`
	AgentID        string      `json:"agent_id"`
	UserID         string      `json:"user_id"`
	Title          string      `json:"title"`
	Explanation    string      `json:"explanation"`
	Reasoning      string      `json:"reasoning"`
	Confidence     float64     `json:"confidence"` // 0.0 to 1.0
	Status         TaskStatus  `json:"status"`
	RequiresReview bool        `json:"requires_review"`
	Tasks          []AgentTask `json:"tasks"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

// AgentTask represents an individual tool invocation step within a plan.
type AgentTask struct {
	ID            string                 `json:"id"`
	PlanID        string                 `json:"plan_id"`
	SequenceIndex int                    `json:"sequence_index"`
	ToolName      string                 `json:"tool_name"`
	Action        string                 `json:"action"`
	Parameters    map[string]interface{} `json:"parameters"`
	IsDestructive bool                   `json:"is_destructive"`
	Status        TaskStatus             `json:"status"`
	Result        string                 `json:"result,omitempty"`
	ErrorMessage  string                 `json:"error_message,omitempty"`
}

// AgentMemory represents operational memory stored by the agent.
type AgentMemory struct {
	ID        string    `json:"id"`
	AgentID   string    `json:"agent_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	Category  string    `json:"category"` // SUCCESS, FAILURE, PREFERENCE, FEEDBACK
	CreatedAt time.Time `json:"created_at"`
}

// AgentFeedback represents user feedback on agent plan proposals.
type AgentFeedback struct {
	ID        string    `json:"id"`
	PlanID    string    `json:"plan_id"`
	UserID    string    `json:"user_id"`
	Approved  bool      `json:"approved"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
}

// AgentExecution represents an execution audit log entry.
type AgentExecution struct {
	ID         string    `json:"id"`
	AgentID    string    `json:"agent_id"`
	PlanID     string    `json:"plan_id"`
	Status     string    `json:"status"`
	DurationMs int64     `json:"duration_ms"`
	Log        string    `json:"log"`
	ExecutedAt time.Time `json:"executed_at"`
}

// AgentPermission represents permissions assigned to an agent.
type AgentPermission struct {
	AgentID        string `json:"agent_id"`
	PermissionName string `json:"permission_name"`
}
